version: '3.8'

services:
  backend:
    build: ./backend
    container_name: todo-backend
    restart: always
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env
    networks:
      - todo-network

  frontend:
    build: ./frontend
    container_name: todo-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5001/api
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge 